# run ruff, black, mypy before every commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: ^podcasts_model_serving
        args: [podcasts_model_serving]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.282
    hooks:
      - id: ruff
        files: ^podcasts_model_serving

  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.4.1
  #   hooks:
  #     - id: mypy
  #       files: ^podcasts_model_serving/
  #       args: [--strict]
  #       additional_dependencies:
  #         - pydantic
    
  - repo: https://github.com/python-poetry/poetry
    rev: 1.3.2
    hooks:
      - id: poetry-check
      - id: poetry-lock